version: '3'

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    command: ["-role", "node", "-hub", "http://selenium-hub:4444/grid/register", "-password", "secret"]
